name: Build Images

on:
  pull_request:
  push:
    branches:
      - master

env:
  TAG: latest

jobs:
  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ['jkube-java-binary-s2i']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install CEKit
        run: ./scripts/install-cekit.sh
      - name: Build java-binary-s2i
        run: |
          echo "Building quay.io/jkube/${{ matrix.image }}/image:${TAG}"
          virtualenv --python=python3 ~/cekit
          source ~/cekit/bin/activate
          cekit --descriptor ${{ matrix.image }}.yaml build docker --tag="${TAG}"
